# Generated by Django 2.1.1 on 2018-10-03 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mosta.base.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('namespace', models.CharField(max_length=10)),
                ('socket_id', models.IntegerField(validators=[mosta.base.validators.positive_number])),
                ('active', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
